- .gitignore
- .travis.yml
- README.md
- testlib-builder/build_tarballs.jl
- testlib-builder/src/testlib/CMakeLists.txt
- testlib-builder/src/testlib/testlib.cpp
This tries to build a test library making use of the libcxxwrap-julia binaries, in an attempt to test and guard against issues like #13.
> Simulate an externally built dependency

- .ci/build_tarballs.jl
- CMakeLists.txt
- FindJulia.cmake
- JlCxxConfig.cmake.in
- testlib-builder/build_tarballs.jl
`Julia_ROOT` is now a reserved variable used by `find_package`(more generally `packagename_ROOT`), and it is always set by cmake from 3.12.
This caused the `Julia_EXECUTABLE` to not be properly set by `FindJulia.cmake`.
Fixing this makes the manual setting of `Julia_EXECUTABLE` in the config cmake file unnecessary.
> Use other variable name than Julia_ROOT

- JlCxxConfig.cmake.in
This commit ensures that JlCxxConfig.cmake does not overwrite the
`CMAKE_MODULE_PATH` set up by the outside environment, which is required
if the caller tries to use `find_package` after loading the JlCxx package.
> Fix JlCxxConfig.cmake changing CMAKE_MODULE_PATH

- examples/basic_types.cpp
- examples/containers.cpp
- examples/except.cpp
- examples/extended.cpp
- examples/functions.cpp
- examples/hello.cpp
- examples/inheritance.cpp
- examples/parametric.cpp
- examples/pointer_modification.cpp
- examples/types.cpp
- include/jlcxx/array.hpp
- include/jlcxx/const_array.hpp
- include/jlcxx/functions.hpp
- include/jlcxx/jlcxx.hpp
- include/jlcxx/module.hpp
- include/jlcxx/smart_pointers.hpp
- include/jlcxx/stl.hpp
- include/jlcxx/tuple.hpp
- include/jlcxx/type_conversion.hpp
- src/c_interface.cpp
- src/functions.cpp
- src/jlcxx.cpp
BOMs (byte order markers) were originally designed for UTF-16 and UTF-32
to be able to deal with both big endian and little endian variants. To
this end, the value 0xFEFF is written as a 16bit or 32bit word at the
start of a text file. By inspecting the first bytes of the file, a text
editor can then determine if the file was written in little or big
endian mode.
For UTF-8, this was never necessary or useful. However, there is still a
BOM standardized for UTF-8, to be able to explicitly mark a file as
being UTF-8 encoded; for this the *byte* sequence EF BB BF has to be at
the start of the file. However, using a UTF-8 BOM is generally not
recommended. Alas, Microsoft tools for some reason insist on it
(presumably due to the historic use of UTF-16 (resp. UCS-2) as default
encoding in …
> Remove non-standard BOMs from C++ source files

- include/jlcxx/type_conversion.hpp
we applied such fix in https://github.com/oscar-system/Polymake.jl/pull/252 due to https://github.com/oscar-system/Polymake.jl/issues/251
> construct std::stringstream from ""

- include/jlcxx/array.hpp
Took the liberty of submitting a PR aiming to complement / fix #58 using the patch described in said issue.
Usage of `auto` can be dropped in favor of explicit typing, if preferrable. Just felt like avoiding redundancy.
> Implement postfix++/-- in array_iterator_base

- include/jlcxx/array.hpp
- include/jlcxx/const_array.hpp
- include/jlcxx/tuple.hpp
- include/jlcxx/type_conversion.hpp
- src/jlcxx.cpp
Creating a new type or allocating an array might garbage collect the given type unless we GC push/pop it.
Perhaps I am mistaken, though, and these types are in no danger of being GC'ed; in this case I'd appreciate a hint why that is so, to further my understanding of this codebase. Thanks!
> Add JL_GC_PUSH / JL_GC_POP calls, reduce usage of jl_svec1

- src/jlcxx.cpp
- test/test_type_init.cpp
These were added in C++11: https://en.cppreference.com/w/cpp/language/types.
> Add support for char16_t and char32_t

- FindJulia.cmake
When using `cmake -DJulia_PREFIX` on Windows, it needs to find `libjulia.dll.a` instead of  `libjulia.dll` to link.
Fix https://github.com/JuliaInterop/CxxWrap.jl/issues/315
> Change julia library search order on Windows

- include/jlcxx/tuple.hpp
this was changed in https://github.com/JuliaLang/julia/pull/49111
for older julia versions this cast should be a no-op
I built libcxxwrap_julia with this change locally with nightly and 1.9, lets see if CI also works.
> julia 1.10: add cast for jl_apply_tuple_type(_v)

- README.md
The corresponding bug has been fixed a while ago. I don't think it's necessary to add a note like "if you see this message, update your version of Julia", because it's been fixed so long ago.
> Remove an obsolete remark in the README, actually fixing #52.

- include/jlcxx/jlcxx_config.hpp
- include/jlcxx/type_conversion.hpp
- src/jlcxx.cpp
Fixes a rare error where type hashes collide, which was due to an incorrect method for creating a key out of `std::type_info`.
> Fix type hash map

- include/jlcxx/array.hpp
for the changes in https://github.com/JuliaLang/julia/pull/51319
cc: @fingolfin 
_Edit:_ The library seems to build but a test module fails with:
```
[ 87%] Linking CXX executable test_module
cd /home/runner/work/libcxxwrap-julia/libcxxwrap-julia/build/test && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/test_module.dir/link.txt --verbose=1
/usr/bin/c++  -Wunused-parameter -Wextra -Wreorder -fPIC -g CMakeFiles/test_module.dir/test_module.cpp.o -o test_module   -L/opt/hostedtoolcache/julia/nightly/x64/lib  -L/opt/hostedtoolcache/julia/nightly/x64/lib/julia  -Wl,-rpath,/opt/hostedtoolcache/julia/nightly/x64/lib:/opt/hostedtoolcache/julia/nightly/x64/lib/julia:/home/runner/work/libcxxwrap-julia/libcxxwrap-julia/build/lib ../lib/libcxxwrap_julia.so.0.11.1 …
```
> julia 1.11: add some workarounds for jl_array changes

- examples/types.cpp
- include/jlcxx/module.hpp
Closes issue https://github.com/JuliaInterop/CxxWrap.jl/issues/374
> Don't store constants as references

- include/jlcxx/array.hpp
My fix from #137 unfortunately triggers an assertion in [PkgEval](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2023-12/15/CxxWrap.primary.log) (i.e. nightly built with assertions enabled):
```
Failed to precompile CxxWrap [1f15a43c-97ca-5a2a-ae31-89f07a497df4] to "/home/pkgeval/.julia/compiled/v1.11/CxxWrap/jl_g65kMF".
julia: /source/src/array.c:277: ijl_array_ptr_1d_push: Assertion `(((((jl_taggedvalue_t*)((char*)(a) - sizeof(jl_taggedvalue_t)))->header) & ~(uintptr_t)15)==(uintptr_t)(jl_array_any_type))' failed.
```
(The code does seem to work fine without assertions)
Switching to `jl_array_ptr_set` avoids that error and should also work across all supported julia versions.
> Array: use jl_array_ptr_set to avoid failed assertion on nightly

- CMakeLists.txt
- examples/functions.cpp
- examples/types.cpp
- include/jlcxx/attr.hpp
- include/jlcxx/module.hpp
- src/c_interface.cpp
Corresponding library functionality for https://github.com/JuliaInterop/CxxWrap.jl/pull/399
> Support for argument names, keyword arguments and argument default values

- README.md
Fixes #143.
Let me know if you would like me to change anything. I just thought this might be useful to document in a central place, considering that the current mismatch between the latest releases of both repositories might trip up other users as well.
> Clarify version compat between libcxxwrap-julia and CxxWrap.jl

- .github/workflows/test-linux-mac.yml
- .github/workflows/test-win.yml
- CMakeLists.txt
- include/jlcxx/julia_headers.hpp
- include/jlcxx/stl.hpp
https://github.com/PraneethJain/CxxWrap.jl#main
> Add StdFill

- .github/workflows/test-linux-mac.yml
- .github/workflows/test-win.yml
- include/jlcxx/jlcxx_config.hpp
- include/jlcxx/stl.hpp
- src/stl.cpp
@PraneethJain This is to prevent too many complications when building a JLL for macOS, we would require to impose a minimum compatibility of macOS 13, which is a bit much at the moment. On the Julia side only a change in the test is needed, see https://github.com/JuliaInterop/CxxWrap.jl/pull/428
> Make range support conditional

- include/jlcxx/stl.hpp
- src/stl.cpp
https://github.com/PraneethJain/CxxWrap.jl#StdSet
Add support for `std::multiset`
> feat: StdMultiset

- include/jlcxx/jlcxx_config.hpp
- include/jlcxx/module.hpp
- include/jlcxx/smart_pointers.hpp
- include/jlcxx/stl.hpp
- include/jlcxx/type_conversion.hpp
- src/jlcxx.cpp
https://github.com/JuliaInterop/CxxWrap.jl#tmp-test-0.13
> Remove type map

- .github/workflows/test-linux-mac.yml
- CMakeLists.txt
- include/jlcxx/stl.hpp
- src/stl.cpp
- src/stl_multiset.cpp
- src/stl_set.cpp
- src/stl_unordered_multiset.cpp
- src/stl_unordered_set.cpp
https://github.com/PraneethJain/CxxWrap.jl#StdUnorderedSet
Add support for `std::unordered_set` and `std::unordered_multiset`
I've used the same wrappers as the ordered set types because they expose the same set functions.
> feat: unordered set types

- include/jlcxx/jlcxx_config.hpp
- include/jlcxx/stl.hpp
- test/CMakeLists.txt
- test/test_module.cpp
https://github.com/JuliaInterop/CxxWrap.jl#main
`std::pair` directly has a `operator<` before c++20, and since it is not treated as a container, `std::set` was being applied to incompatible types. The tests weren't failing here because since c++20 `<=>` is used to synthesize `operator<`  (https://en.cppreference.com/w/cpp/utility/pair/operator_cmp)
Because of this, inconsistent behavior was being observed
https://pastebin.ai/0stwtqgvry
The above program outputs different values for c++17 and c++20
This PR fixes this issue by explicitly checking if the pair types are comparable.
> fix: check if std::pair has less than

- CMakeLists.txt
- include/jlcxx/stl.hpp
- src/stl.cpp
- src/stl_stack.cpp
https://github.com/PraneethJain/CxxWrap.jl#linear-containers
- Removed `AbstractVector` as parent type for `StdQueue`. This was causing errors when printing a queue, because it expects `Base.iterate` for the queue to be implemented, which hasn't been done as of now .
- Added `std::stack` support
> Add `std::stack` and fix `std::queue` methods

- include/jlcxx/stl.hpp
https://github.com/PraneethJain/CxxWrap.jl#stl-algos
Added support for `std::lower_bound`, `std::upper_bound`, `std::binary_search`, `std::fill`, and `std::list::sort` to the appropriate containers.
Removed `std::fill` from `std::vector`, `std::valarray` and `std::deque` as they already work on the Julia side.
Similarly, sort, min, max, etc. already work on the Julia side due to the correct parent types being assigned.
> Add support for common STL algorithms

- include/jlcxx/stl.hpp
https://github.com/JuliaInterop/CxxWrap.jl#main
Explicit return types are not needed as the correct types are inferred directly.
> misc: remove redundant return types

- .github/workflows/test-linux-mac.yml
- examples/types.cpp
- include/jlcxx/jlcxx_config.hpp
- include/jlcxx/stl.hpp
- src/stl.cpp
- src/stl_deque.cpp
- src/stl_forward_list.cpp
- src/stl_list.cpp
- src/stl_multiset.cpp
- src/stl_priority_queue.cpp
- src/stl_queue.cpp
- src/stl_set.cpp
- src/stl_stack.cpp
- src/stl_unordered_multiset.cpp
- src/stl_unordered_set.cpp
- src/stl_valarray.cpp
- src/stl_vector.cpp
- test/test_module.cpp
https://github.com/JuliaInterop/CxxWrap.jl#stl-updates
This should shorten macOS compile times again and fix problems with attempts
to put non-comparable types into e.g. `std::set`.
> Make application of STL wrappers more fine grained

- include/jlcxx/jlcxx_config.hpp
- src/c_interface.cpp
- src/jlcxx.cpp
https://github.com/JuliaInterop/CxxWrap.jl#stl-updates
Creating a new `jlcxx::Array<...>()` calls `jl_alloc_array_1d` which can trigger garbage collection. Thus we need to protect each array before creating the next one, instead of doing one `JL_GC_PUSH6` call here:
https://github.com/JuliaInterop/libcxxwrap-julia/blob/d4192fe3ea20829bd399d812863abd8303f9bcab/src/c_interface.cpp#L138-L146
This might help with some rare crashes during initialization or precompilation we have seen in the Oscar CI for quite a while (see https://github.com/oscar-system/Oscar.jl/issues/3296).
The backtrace I got locally was:
```julia
Precompiling Oscar...                                              
5 dependencies successfully precompiled in 242 seconds. 113 already precompiled.
[16014] signal 11 (1): …
```
> get_module_functions: separate gc pushes

- .github/workflows/test-linux-mac.yml
- examples/functions.cpp
- examples/inheritance.cpp
- examples/types.cpp
- include/jlcxx/functions.hpp
- include/jlcxx/jlcxx_config.hpp
- include/jlcxx/module.hpp
- src/functions.cpp
- src/jlcxx.cpp
https://github.com/JuliaInterop/CxxWrap.jl#newenum
Adds enums by calling `@enum` internally, ensuring full compatibility with the way enums are expected to work in Julia.
> Add proper enum support
