JuliaInterop/libcxxwrap-julia

- include/jlcxx/jlcxx_config.hpp
- include/jlcxx/module.hpp
- include/jlcxx/type_conversion.hpp
- src/c_interface.cpp
- src/jlcxx.cpp
- test/cxxwrap_testmod.jl
- test/test_module.cpp
C++ part of the fix for https://github.com/JuliaInterop/CxxWrap.jl/pull/136
> Move GC protect code to Julia

- include/jlcxx/array.hpp
see https://github.com/JuliaInterop/libcxxwrap-julia/issues/26
> fix templates in array_iterator_base arithmetic

- .ci/build_tarballs.jl
- .travis.yml
- appveyor.yml
- include/jlcxx/module.hpp
Attempt to fix tests after last changes
> Fix tests after init changes

- include/jlcxx/module.hpp
Issue #203
Also try to debug a segfault on Nightly.
> Add signed char type

- examples/types.cpp
- include/jlcxx/module.hpp
- include/jlcxx/smart_pointers.hpp
- include/jlcxx/stl.hpp
- src/c_interface.cpp
- src/jlcxx.cpp
This is the C++ part of the fix for https://github.com/JuliaInterop/CxxWrap.jl/issues/192
> Assign pointer indices on the Julia side

- examples/basic_types.cpp
- include/jlcxx/module.hpp
- include/jlcxx/stl.hpp
- include/jlcxx/type_conversion.hpp
- src/c_interface.cpp
- src/jlcxx.cpp
- test/test_type_init.cpp
Issue https://github.com/JuliaInterop/CxxWrap.jl/issues/203
> Refine integer type mapping

- README.md
> Add more detail about Julia paths

- README.md
See https://github.com/JuliaInterop/CxxWrap.jl/pull/251
> README.md: mention that a C++17 compiler is required

- FindJulia.cmake
See https://github.com/JuliaPackaging/Yggdrasil/pull/1948#discussion_r511532755
> Add fixes for building on Yggdrasil

- src/jlcxx.cpp
See https://github.com/JuliaPackaging/Yggdrasil/pull/3263﻿
> Compatibility with Julia 1.7

- examples/types.cpp
- include/jlcxx/module.hpp
This should fix https://github.com/JuliaInterop/CxxWrap.jl/issues/289
> Only add finalizer for types that are destructible

- .github/workflows/test-linux-mac.yml
- .github/workflows/test-win.yml
- .gitignore
- CMakeLists.txt
- examples/except.cpp
- include/jlcxx/jlcxx.hpp
- include/jlcxx/jlcxx_config.hpp
- include/jlcxx/julia_headers.hpp
- include/jlcxx/type_conversion.hpp
- src/jlcxx.cpp
- test/test_cxxwrap.cpp
- test/test_module.cpp
- test/test_type_init.cpp
Adapt headers as suggested in https://github.com/JuliaLang/julia/issues/34201#issuecomment-817081705 and https://github.com/JuliaLang/julia/issues/39595#issuecomment-817080505
> Fix headers for MSVC

- src/stl.cpp
> Stdthreads

- include/jlcxx/tuple.hpp
> Fix compilation against Julia 1.11

- examples/functions.cpp
- examples/hello.cpp
- include/jlcxx/module.hpp
- src/c_interface.cpp
Adds an optional argument "doc" to `method(...)` which can be used in CxxWrap.jl to add a `Core.@doc` annotation.
> docstring support for method(...)

- .github/workflows/test-linux-mac.yml
- .github/workflows/test-win.yml
- examples/inheritance.cpp
- examples/types.cpp
- include/jlcxx/module.hpp
- include/jlcxx/smart_pointers.hpp
- include/jlcxx/type_conversion.hpp
- src/stl.cpp
Issue https://github.com/JuliaInterop/CxxWrap.jl/issues/405
> Fixes for const template parameters

- include/jlcxx/jlcxx_config.hpp
- include/jlcxx/module.hpp
https://github.com/JuliaInterop/CxxWrap.jl#dynamiccast
> Add support for dynamic casting in Julia

- .github/workflows/test-linux-mac.yml
- examples/types.cpp
- include/jlcxx/stl.hpp
- src/stl.cpp
https://github.com/PraneethJain/CxxWrap.jl#StdSet
Add support for `std::set`
> feat: StdSet

- examples/inheritance.cpp
- include/jlcxx/jlcxx_config.hpp
- include/jlcxx/module.hpp
Issue Regression with 0.12.3 in the support of static inheritance #156
> Fix static inheritance problem

- .github/workflows/test-linux-mac.yml
- CMakeLists.txt
- include/jlcxx/jlcxx_config.hpp
- include/jlcxx/stl.hpp
- src/stl.cpp
- src/stl_deque.cpp
- src/stl_multiset.cpp
- src/stl_queue.cpp
- src/stl_set.cpp
- src/stl_shared_ptr.cpp
- src/stl_unique_ptr.cpp
- src/stl_valarray.cpp
- src/stl_vector.cpp
- src/stl_weak_ptr.cpp
https://github.com/JuliaInterop/CxxWrap.jl
> Split up STL compilation

- CMakeLists.txt
- include/jlcxx/stl.hpp
- src/stl.cpp
- src/stl_priority_queue.cpp
https://github.com/PraneethJain/CxxWrap.jl#priority-queue
Add `std::priority_queue`
> feat: add priority queue

- CMakeLists.txt
- include/jlcxx/stl.hpp
- src/stl.cpp
- src/stl_forward_list.cpp
- src/stl_list.cpp
https://github.com/PraneethJain/CxxWrap.jl#lists
Added STL list types
> feat: add std::list and std::forward_list

- include/jlcxx/array.hpp
https://github.com/JuliaInterop/CxxWrap.jl#stl-updates
Issue https://github.com/JuliaInterop/CxxWrap.jl/issues/260
> Integrate changes needed for OpenCV

- .github/workflows/test-linux-mac.yml
- .github/workflows/test-win.yml
- examples/containers.cpp
- include/jlcxx/array.hpp
- include/jlcxx/jlcxx_config.hpp
- include/jlcxx/stl.hpp
> Fix https://github.com/JuliaInterop/CxxWrap.jl/issues/473

- examples/containers.cpp
- include/jlcxx/array.hpp
- include/jlcxx/stl.hpp
- include/jlcxx/tuple.hpp
https://github.com/JuliaInterop/CxxWrap.jl#tuple-fixes
> Tuple fixes

- examples/containers.cpp
https://github.com/JuliaInterop/CxxWrap.jl#string-array
> Add string array test
